baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = ''

theme = "ananke"

[params]
  highlightjs = false
  custom_css = ["css/chroma-silent.css"]

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = false
    lineNos = false
