baseURL = 'https://xuezhixiachongnai.github.io/'
languageCode = 'zh-cn'
title = ''

theme = "ananke"

[params]
  highlightjs = false

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = false
    lineNos = false
